common: &common
 adapter: postgresql
 encoding: utf8
 host: localhost

development:
 <<: *common
 database: pod_dev
 username: pod_dev
 password: pod_dev

test:
 <<: *common
 database: pod_test
 username: pod_test
 password: pod_test